Update tip documents
iZettle/sdk-android pull request #42
Opened 2021-10-27 13:28 UTC by AndreaFilyo

Accessibility updates: Uploaded new images, created new md files for tipping flows and in-app pairing, replacing the existing PDF files. Removed the existing PDF files. Updated the Tipping support doc with links to the new md files.

2021-11-01 10:10 UTC, bobzettle requested changes

2021-11-01 10:10 UTC, bobzettle commented on Documentation/In-app Pairing Guide.md
> +1. Go to **Zettle Settings** and select **Card readers** to connect the Zettle Reader 2 from the SDK.<br>
On Android we don't have a **Zettle Settings** view. You open the card readers settings directly.

2021-11-01 10:10 UTC, bobzettle commented on Documentation/In-app Pairing Guide.md
> +4. Select **Zettle Reader 2**. Note that other card readers can be connected from the iOS Bluetooth settings.
```suggestion
4. Select **Zettle Reader 2**. Note that other card readers can be connected from the Android Bluetooth settings.
```

2021-11-01 10:10 UTC, bobzettle commented on Documentation/In-app Pairing Guide.md
> +11. To forget a card reader, go to the Card reader detail view. Note that forgetting a card reader can no longer be done from the iOS Bluetooth settings.<br>
```suggestion
11. To forget a card reader, go to the Card reader detail view. Note that forgetting a card reader can no longer be done from the Android Bluetooth settings.<br>
```

2021-11-01 10:10 UTC, bobzettle commented on Documentation/Tipping_flow_on_the_Zettle_card_reader/Total Amount Tipping Flow.md
> +There is a maximum level validation to prevent accidental or invalid entering of amounts. This can happen for example if customers enter their PIN code instead of a tip amount. The maxium tip level i
I don't think the max tip limit is an exact number? 
Isn't it different in different markets?

2021-11-01 10:27 UTC, AndreaFilyo commented on Documentation/Tipping_flow_on_the_Zettle_card_reader/Total Amount Tipping Flow.md
> +There is a maximum level validation to prevent accidental or invalid entering of amounts. This can happen for example if customers enter their PIN code instead of a tip amount. The maxium tip level i
OK, should I remove this part then? "The maximum tip level is 35 %"? (there was a typo there as well...)

2021-11-02 18:42 UTC, AndreaFilyo commented on Documentation/Tipping_flow_on_the_Zettle_card_reader/Total Amount Tipping Flow.md
> +There is a maximum level validation to prevent accidental or invalid entering of amounts. This can happen for example if customers enter their PIN code instead of a tip amount. The maxium tip level i
Removed mentioning of tipping level value, as discussed.

2021-11-02 18:45 UTC, AndreaFilyo commented
Final fixes. Related Jira ticket: DEVX-641

2021-11-02 18:46 UTC, merged